### ISSUE TITLE
Finalize navigation menu styling + logic

### ISSUE THREAD

**Issue by obpFin** [montel-ig/westend-indians#31]
"Nyt kun Heimo-sivun alla on alasivuja ja klikkaa esim infoa, niin kadottaa tuon toisen navigointipalkin. Varmaan saa pidettyä mukana sen kakkostason palkin myös alasivuilla ja korostettua sen?"

**Comment by luopio** [comment]
Child child pages now work with visible menu and correct active parent pages are displayed with the startswith template filter. Still needs the decision on if we want the hover menu
