### ISSUE TITLE
Sponsorit & Lopetus

### ISSUE THREAD

**Issue by luopio** [montel-ig/westend-indians#35]
SPONSORIT & LOPETUS

~~https://www.hjk.fi (muuten samanlainen paitsi tähtien klubi pois) eli mm. eka sponssit ja sitten lopetus~~
Otsikointia ei tarvitse vaan voi olla vain koon mukaan + vähän tiiviimmin
~~Musta/valko ja päälle vietäessä väri~~
~~Someikonit: Face, Instagram, Twitter, Youtube, Flickr~~
~~Myös tuo lopetus samaan muottiin (logoja max. 5 kpl tulossa)~~

**Comment by obpFin** [comment]
Sponssilogoista olisi toiveena viilaus: pääkumppanit isommalla logolla ja max 5 logoa rivilleen (alkuun käytettäisiin 3 logoa tässä). 2. kategoriassa logoja pitäisi mahtua 8 riville ja 2 riviä. Alkuun käytettäisi 8+4 logoa. Kolmoskategoriassa 10 logoa per rivi ja kolme riviä käyttöön (alkuun käytettäisi 10+10 eli kaksi täyttä riviä).

Ja sivun alareunaan vielä tulisi alkuun kolme logoa (ei sponsseja vaan espoon kaupunki,  maajoukkuetie, salibandyliiga jne). Tässä tarvitsisi varauksen yhteensä kuudelle logolle sille riville.
